name: Elratam
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.3.10 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Utilities
  url_launcher: ^6.1.10
  image_picker: ^1.2.1
  app_settings: ^7.0.0
  dio: ^5.4.3+1 # For downloading files
  path_provider: ^2.1.3 # To find download path
  permission_handler: ^11.3.1 # To request storage permissions

flutter:
  uses-material-design: true

  assets:
    - elratamapp/assets/logo.png
    - elratamapp/assets/app_icon.png
    - elratamapp/assets/google_logo.png
    - elratamapp/assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: elratamapp/assets/fonts/OpenSans-Regular.ttf
        - asset: elratamapp/assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: elratamapp/assets/fonts/Roboto-Regular.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "elratamapp/assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "elratamapp/assets/logo.png"
